#!/bin/bash

echo "Running flake8..."

flake8 python_scripts --config .github/workflows/.flake8

if [ $? -ne 0 ]; then
    echo "Linting failed. Fix the errors and try again."
    exit 1
fi

echo "Running unit tests..."

python3 python_scripts/sync_announcement_test.py

if [ $? -ne 0 ]; then
    echo "Unit tests failed. Fix the errors and try again."
    exit 1
fi

COMMIT_MSG_FILE=$1

SANITIZED_MSG=$(cat $COMMIT_MSG_FILE | tr -cd 'a-zA-Z0-9 ')
echo "$SANITIZED_MSG" > $COMMIT_MSG_FILE